### ISSUE TITLE
C# WASMIF wrapper

### ISSUE THREAD

**Issue by mpaperno** [jldowson/FSUIPC_WAPI#5]
Hi John,

As mentioned, I made a C# assembly for `WASMIF` class.  It's a C++/CLI style wrapper, using the C++ code/library directly vs. requiring a DLL.  The C/CLI stuff was definitely a new one for me (as is C# for that matter), and I kinda like it (best of both worlds, more or less).

Originally I just linked it against the static libs you had published on your site. So it doesn't require the actual library code, just the usual header.  But seemed to make the most sense (to me) to combine them into the same solution/repo.  

(In fact, it took me a while to find this repo at all, originally all I found were the static libs on your site, then later the DLL version, then the other general FSUIPC wrapper, then finally...  :)

It pretty much just replicates the functionality/methods of  `WASMIF`, with some basic changes for CS like event delegates for callbacks and of course some type conversions (containers and strings).   Pretty simple really... originally it all just fit comfortably into the header file, but I moved some stuff to .cpp for "propriety."

The project itself is here  https://github.com/mpaperno/FSUIPC_WAPI/tree/mp/main/FSUIPC_WAPI_CS

There is a branch with [just the new project](https://github.com/mpaperno/FSUIPC_WAPI/commits/mp/cs-wrapper), and it's also pushed to my `mp/main` default branch.

The first commit on the side branch you'll notice adds a way to get the current starting ID number.  I added that as a way to notify the CS library user if they try to request a new instance with a different ID than the first (since that won't work).  I'm actually vague on why the whole WASMIF is essentially static, or rather if it's even possible to run multiple WAPI clients at the same time with different IDs  (seems like it should be...?  unless on the WASM side only one client can be handled at a time?).

As an aside, on my main branch I also added a little [distro script](https://github.com/mpaperno/FSUIPC_WAPI/commit/70597d3288ad96bcd57b15462b9e940fb127ed0c) for the static lib you may like... besides just basic file copying, it strips out all the unnecessary stuff from the WASMIF.h header, leaving only what's needed for consuming the static lib.  I also pushed a distro folder with latest binaries.

Anyhow, let me know if any interest or questions. I can certainly PR it, or you're welcome to clone/merge it yourself of course.  If you think it should be a separate project/repo, let me know as well and I can easily separate it out into a standalone version (with included static lib and headers dependencies like eg. your DLL or client example projects).

Best,
-Max

**Comment by jldowson** [comment]
It should certainly be in a separate repo. I already provide a light-way wrapper that can be used - see my FSUIPC_WDLL project.
This is used by Paul Henty's client dll for .Net, which is what I suggest people use if they want to use a C# API for the WAPI (it is also the preferred C# API for the FSUIPC SDK).
I won't be merging this in as I would like to keep the WAPI project as just for the C/C++ API.

Cheers,
John

**Comment by mpaperno** [comment]
Alrighty, no problem.  I already outlined in the other issue why the DLL or Paul's offering didn't work for me so I won't repeat that.  This one is a lot more direct and would be easier to keep updated, and doesn't take liberties with what a user of the API may or may not want to do.

I'll keep it on my fork for now, feel free to point to it if you wish.

Best,
-Max
